apiVersion: rancher.k8s.binbash.org/v1beta1
kind: FloatingIP
metadata:
  name: fip-12345
  namespace: p-12345
  labels:
    rancher.k8s.binbash.org/project-name: p-12345
spec:
  floatingIPPool: rke2-bm-aio--public-vlan-1
  ipAddr: 192.168.100.10
---
apiVersion: rancher.k8s.binbash.org/v1beta1
kind: FloatingIP
metadata:
  name: fip-54321
  namespace: p-54321
  labels:
    rancher.k8s.binbash.org/project-name: p-54321
spec:
  floatingIPPool: rke2-bm-aio--public-vlan-1