apiVersion: v1
kind: Namespace
metadata:
  labels:
    rancher.k8s.binbash.org/project-name: p-12345
  name: p-12345
spec: {}
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    rancher.k8s.binbash.org/project-name: p-54321
  name: p-54321
spec: {}